In [7]:
import numpy as np
import pandas as pd
from os import listdir
from os.path import join

In [3]:
raw_csv = pd.read_csv('/home/ryan/cs/datasets/tsa/stage1/labels.csv')

In [36]:
raw_csv[20:50]

                                         Id  Probability
20  0043db5e8c819bffc15261b1f1ac5e42_Zone12            0
21  0043db5e8c819bffc15261b1f1ac5e42_Zone13            0
22  0043db5e8c819bffc15261b1f1ac5e42_Zone14            1
23  0043db5e8c819bffc15261b1f1ac5e42_Zone15            0
24  0043db5e8c819bffc15261b1f1ac5e42_Zone16            0
25  0043db5e8c819bffc15261b1f1ac5e42_Zone17            0
26   0043db5e8c819bffc15261b1f1ac5e42_Zone2            0
27   0043db5e8c819bffc15261b1f1ac5e42_Zone3            0
28   0043db5e8c819bffc15261b1f1ac5e42_Zone4            0
29   0043db5e8c819bffc15261b1f1ac5e42_Zone5            0
30   0043db5e8c819bffc15261b1f1ac5e42_Zone6            0
31   0043db5e8c819bffc15261b1f1ac5e42_Zone7            0
32   0043db5e8c819bffc15261b1f1ac5e42_Zone8            0
33   0043db5e8c819bffc15261b1f1ac5e42_Zone9            1
34   0050492f92e22eed3474ae3a6fc907fa_Zone1            0
35  0050492f92e22eed3474ae3a6fc907fa_Zone10            0
36  0050492f92e22eed3474ae3a6fc907fa_Zone11            0
37  0050492f92e22eed3474ae3a6fc907fa_Zone12            0
38  0050492f92e22eed3474ae3a6fc907fa_Zone13            0
39  0050492f92e22eed3474ae3a6fc907fa_Zone14            0
40  0050492f92e22eed3474ae3a6fc907fa_Zone15            0
41  0050492f92e22eed3474ae3a6fc907fa_Zone16            1
42  0050492f92e22eed3474ae3a6fc907fa_Zone17            0
43   0050492f92e22eed3474ae3a6fc907fa_Zone2            0
44   0050492f92e22eed3474ae3a6fc907fa_Zone3            0
45   0050492f92e22eed3474ae3a6fc907fa_Zone4            1
46   0050492f92e22eed3474ae3a6fc907fa_Zone5            0
47   0050492f92e22eed3474ae3a6fc907fa_Zone6            0
48   0050492f92e22eed3474ae3a6fc907fa_Zone7            0
49   0050492f92e22eed3474ae3a6fc907fa_Zone8            1

In [34]:
num_zones = 17
new_df = pd.DataFrame(columns=('Id', 'Label'))
curr_name = ''
curr_count = 0
curr_image = 0

for index, row in raw_csv.iterrows():
    # same image, different zone
    if row['Id'].split('_')[0] == curr_name and curr_count < num_zones:
        one_hot[int(row['Id'].split('_')[1][4:])-1] = row['Probability']
        curr_count += 1
    # start a new image
    elif row['Id'].split('_')[0] != curr_name and (curr_count == num_zones or curr_count == 0):
        # dump previous image
        if curr_count != 0:
            new_df.loc[curr_image] = [curr_name, one_hot]
            curr_image += 1
        
        one_hot = np.zeros(num_zones)
        one_hot[int(row['Id'].split('_')[1][4:])-1] = row['Probability']     
        curr_name = row['Id'].split('_')[0]      
        curr_count = 1
    else:
        print('Error: zones not consistent with path name.')
        break

In [35]:
new_df.head()

,Id,Label
0,00360f79fd6e02781457eda48f85da90,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,0043db5e8c819bffc15261b1f1ac5e42,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, ..."
2,0050492f92e22eed3474ae3a6fc907fa,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, ..."
3,006ec59fa59dd80a64c85347eef810c7,"[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,0097503ee9fa0606559c56458b281a08,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [37]:
new_df.to_csv('formatted_labels.csv')